// <auto-generated />
using GdMAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GdMAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231129030312_InnitialCreate")]
    partial class InnitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GdMAPI.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_MATERIAL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "Preto",
                            Marca = "FaberCastell",
                            Nome = "Lápis",
                            Quantidade = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Cor = "Azul",
                            Marca = "BIC",
                            Nome = "Caneta",
                            Quantidade = 1,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Cor = "Branco",
                            Marca = "Mercur",
                            Nome = "Borracha",
                            Quantidade = 1,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 4,
                            Cor = "Transparente",
                            Marca = "Cis",
                            Nome = "Apontador",
                            Quantidade = 1,
                            Tipo = 4
                        },
                        new
                        {
                            Id = 5,
                            Cor = "Vermelho",
                            Marca = "Spriral",
                            Nome = "Caderno",
                            Quantidade = 1,
                            Tipo = 7
                        },
                        new
                        {
                            Id = 6,
                            Cor = "Cinza",
                            Marca = "SAE",
                            Nome = "Livro",
                            Quantidade = 1,
                            Tipo = 8
                        },
                        new
                        {
                            Id = 7,
                            Cor = "Azul",
                            Marca = "Kipling",
                            Nome = "Mochila",
                            Quantidade = 1,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 8,
                            Cor = "Cinza",
                            Marca = "Genérica",
                            Nome = "Estojo",
                            Quantidade = 1,
                            Tipo = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
